### PR TITLE
Update ru.json

### PR DESCRIPTION
**Pull request by EdwardGeneralov**
3 translated

### CODE REVIEW

**Comment by RazeSoldier** [comment]
Hi, EdwardGeneralov. This repository is a mirror from gerrit.wikimedia.org. So we don't accept any PR. We translate localisations of mediawiki via translatewiki.net. See https://www.mediawiki.org/wiki/Localisation.

**Comment by EdwardGeneralov** [comment]
@RazeSoldier you can translate mediawiki message without translatewiki.net, translatewiki.net coming loaded FuzzyBot of MediaWiki message.

**Comment by LunarTwilight** [comment]
@EdwardGeneralov translations are done on translatewiki.net, not here. Also this repo is a one way mirror, so changes here won't be synced to gerrit.

**Comment by EdwardGeneralov** [comment]
@LunarTwilight here translating without using translatewiki.net coming imported FuzzyBot.

**Comment by amire80** [comment]
@EdwardGeneralov, this pull request will not be accepted. There are several reasons for this:

1. This is only a mirror and pull requests are never accepted. The code is contributed only through Gerrit and never through GitHub. See https://www.mediawiki.org/wiki/Gerrit .

2. Translations are not accepted even through Gerrit, but only through translatewiki.net . If you have issues with FuzzyBot, please bring them up at https://translatewiki.net/wiki/Support .

3. This pull request is generally wrong. The strings in this pull requests don't belong to MediaWiki core, but to its extensions: VisualEditor and SemanticMediaWiki. The extensions are also translated only at translatewiki.net .

**Comment by RazeSoldier** [comment]
As I know,  FuzzyBot is a system user that build-in to [translation extension](https://www.mediawiki.org/wiki/Extension:Translate). Nothing to do with the localization of mediawiki core.

**Comment by EdwardGeneralov** [comment]
Closed, There are no new messages of TranslateWiki.net don't loaded FuzzyBot message, Oops!

**Pull request closed without merging**
