### PR TITLE
Hyphen to dash for range

### PR DESCRIPTION
**Pull request by vanillajonathan**

### CODE REVIEW

**Comment by LunarTwilight** [comment]
Hi @vanillajonathan. This Github repo is a mirror, and the real repo is on gerrit.wikimedia.org. You might also want to read https://www.mediawiki.org/wiki/Developer_access

**Comment by vanillajonathan** [comment]
Oh I don't have any account there and just this small commit, could someone manually merge this?

**Comment by Krinkle** [comment]
I've uploaded it using <https://tools.wmflabs.org/gerrit-patch-uploader/>.

It's now up for review at <https://gerrit.wikimedia.org/r/#/c/372453/2>.

**Comment by vanillajonathan** [comment]
Thank you! 👍

**Pull request closed without merging**
